#!/usr/bin/env ruby

$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), 'lib'))

require 'icfpc2012'

alias :original_puts :puts
alias :original_pring :print
def puts(*); end
def print(*); end

begin

  map = Icfpc2012::Map.new($stdin.read)
  sc = Icfpc2012::Scheduler.new(map)
  begin
    result = sc.solve

    if ARGF.argv != [] && ARGF.argv[0] == "--verbose"
      original_puts result[0]
      original_puts result[1]
    else
      original_puts result.first
    end
  ensure
    original_puts sc.best_solution
    #exit 0
  end
end
